spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb+srv://grzegorzsz884:pafMsXbnGnG7mYVS@cluster0.izpwq5x.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: product

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka